### ISSUE TITLE
Výpl.páska email

### ISSUE THREAD

**Issue by 61Stan** [eurosecom/projekt1#143]
Zamestnancom posielanie výplatných pások cez email. Skúšal som: mail sa pošle ale chýba príloha = výplatná páska zamestnanca.

**Comment by eurosecom** [comment]
Dal som na edcom.sk a euroalchem.sk.

**Comment by eurosecom** [comment]
Ak chcú používať výplatné pásky do mailu namiesto podpisovania papierovej mali by
1. Písomný dodatok pracových zmlúv, o elektronickom zasielaní výplatnej pásky, kde uvedú email zamestnanca kam mu budú posielať pásku
2. Zriadiť emailovú schránku napr. pasky@euroalchem.sk kam sa budú posielať kópie odoslaných výplatných pások ako doklad o odoslaní pretože webové mailovanie nemá históriu odoslanej pošty. Ten komunikačný mail sa nastaví do toho mailovacieho skriptu.

**Comment by 61Stan** [comment]
Bod 1. i 2. si porieši. Povedala, že môžeme vyskúšať aj s "pasky@euroalchem.sk

**Comment by 61Stan** [comment]
Funkčné vo všetkých bodoch
