### ISSUE TITLE
Odvodový bonus ZP 2015 a el.súbor ZP 2015

### ISSUE THREAD

**Issue by eurosecom** [eurosecom/projekt1#49]
Znnížené odvody do ZP v roku 2015.

**Comment by 61Stan** [comment]
Vo formulári je ikona pre načítanie z minulého roka. Má to nejaký význam, keď v roku 2015 prvýkrát používajú?

**Comment by eurosecom** [comment]
nema moze sa schovat

**Comment by 61Stan** [comment]
Odkaz "Odpočet v ZP" je vidieť aj vo firme roku 2014, ale vtedy ešte neplatilo.

**Comment by eurosecom** [comment]
ZP Dôvera -> ak pomer 14 treba nastaviť sadzby 10 a 4 aj keď neplatí.
www.vppsro.sk
firma 176
os.č. 202
mzdy 5.2015
Ide o dlhodobo nezamestnanú, ktorá neplatí odvody na zdravotnú, ale má na výkazy zobrazovať sadzby 10.00 a 4.00. V papierovej forme tak program dáva, ale v elektronike nie.
