### ISSUE TITLE
UCTO Priznanie DMV rok 2014 

### ISSUE THREAD

**Issue by eurosecom** [eurosecom/projekt1#61]
Výpočet predpokladanej dane na rok 2015.

**Comment by eurosecom** [comment]
Je to flash uprava nie je to odskusane ale p.Kákošová by to mohla otestovať !!??!!
Po kliknutí na kalkulačku predpoklad to vypočíta sadzby z novej tabuľky, bolo by dobré skontrolovať _sadzby_dmv2015 na lokaly ked to spustíš mne už s to zlieva dokopy...
Keď to vypočíta dole v okne dá taky flash výpis toho čo vypočítal pre kontrolu...
![dmvpredpoklad2015](https://cloud.githubusercontent.com/assets/8501403/5765724/2ab1cfde-9cfc-11e4-8c39-9a281774a207.png)

**Comment by 61Stan** [comment]
p. Kákošová bude testovať budúci týždeň. Skôr mi na čele robí vrásky p. Valachovičová. Už mi 3x volala, či je to už v programe.
