### ISSUE TITLE
MZDY RZ prenos do miezd

### ISSUE THREAD

**Issue by 61Stan** [eurosecom/projekt1#70]
Vo formulári ročného zúčtovania 2014, ak použijú prenos preplatku/nedoplatku z RZ do firmy, mesiaca a kód (vpravo hore v záhlaví tlačiva), tak sa stane nasledujúca situácia: majú už 1.2015 spracovaný, ale omylom dajú prenos z tlačiva ročného zúčtovania. Zistia omyl, a chcú zrušiť ostré. Ale zrušiť ostré už im nechce, pretože je tam nahraté po ostrom spracovaní niečo. Príde telefonát, čo s tým. Tak príjde vysvetlenie: v mesačnej mzde musia dať tlačiareň, aby videli, kto je nahratý po ostrom. A potom im podať vysvetlenie, ako vymazať. Podľa mňa lepšie hlášku do tlačiva 2014, že nemôžu prenášať do 1.2015, pretože už majú ostré a nedovoliť prenos.

**Comment by eurosecom** [comment]
kontrolujem a upozornujem dnes ide do upgrade
