### ISSUE TITLE
Všeobecné podanie DÚ

### ISSUE THREAD

**Issue by eurosecom** [eurosecom/projekt1#71]
Vyplnenie, tlač a XML export

**Comment by 61Stan** [comment]
Je vidieť v roku 2013, čo nie je dobre.

**Comment by eurosecom** [comment]
??????

**Comment by 61Stan** [comment]
Keď sa prepnem do firmy roku 2013, tak všeobecné podanie je vidieť v danprij.php.

**Comment by 61Stan** [comment]
Budeme musieť prekopať (názov súboru = "vseobecne_podanie.php") pre rok 2015, pretože v eDane sú rozdelené všeobecné podania k účtovnej závierke podľa druhu účtovnej jednotky a typu účtovníctva = Všeobecné podanie k ÚZ v PÚ (VP-PODv15 = jediné máme), Všeobecné podanie k ÚZ v JÚ (VP-UVFOv15), Všeobecné podanie k ÚZ v PÚ pre NÚJ (VP-UVNUJv15) a Všeobecné podanie k ÚZ v JÚ pre NÚJ (VP-UVNOv15). Alebo všeobecné podanie spravíme univerzálne = ošetrenie <selector> podľa druhu účtovníctva a typu účtovnej jednotky.

**Comment by 61Stan** [comment]
Toto issue, asi už nebude platné, keď rozdeľujeme na pod a núj
