### ISSUE TITLE
MAJ Nulové odpisy zrušenie

### ISSUE THREAD

**Issue by 61Stan** [eurosecom/projekt1#74]
Ak v mesiaci mám nulový odpis, tak síce spravím odpisy, ale už mi ho nedá do prehľady a rušenie mesačných odpisov.

**Comment by eurosecom** [comment]
Odpis moze byt nulovy to nevadi ale ak nemam ani jednu polozku majetku na stave tak síce spravím odpisy, ale už mi ho nedá do prehľady a rušenie mesačných odpisov.

**Comment by eurosecom** [comment]
dal som na edcom.sk/majetok a 20.2.2015 do upgrade
