### ISSUE TITLE
UČTO Poznámky účpod verzus závierka účpod

### ISSUE THREAD

**Issue by 61Stan** [eurosecom/projekt1#75]
Po načítaní údajov do "Účtovná závierka Úč POD v.2014" nesedia tabuľky 26cd, 35 a 38 (riadok Čistý obrat) s účtovnou závierkou. Môžete pozrieť v Sekov. Mne na locale tiež nesedelo.

**Comment by eurosecom** [comment]
Tabulka 26cd a 35 je co ? Poznamky POD ? Lebo v tab 26cd a 35 riadok Cisty obrat nie je ? Teda nesedi cisty obrat v tabulke 38 Poznamok POD oproti riadku 01 Uzavierky POD ?

**Comment by 61Stan** [comment]
Týka sa to Poznámky Úč POD 3 - 01 k DPPO verzia 2014. Tabuľka 26cd = Záväzky, Tabuľka 35 = Tržby. Tabuľka 38 = Čistý obrat = tu nesedí čistý obrat celkom s vzas 1.riadok.

**Comment by eurosecom** [comment]
a v tej tabulke 26cd co provnavaju s cim ?
a v tabulke 35 co porovnavaju s cim ?

**Comment by eurosecom** [comment]
Vo Vykaze ziskov je riadok 01  cast uct.triedy 6 trzby za tovar, vyrobky a sluzby r01=r03+r04+r05  a podla poucenia by to malo byt este bez poskytnutych zliav ??!!??!!??!!??
V Poznamkach v tabulke 38 je v riadku "Čistý obrat celkom " súčet riadkov nad ním a tam je aj "Iné výnosy súvisiace s bežnou činnosťou" a ďalšie dva riadky.
Treba reklamovať na MF, že používajú skoro rovnaké pojmy pre dve veci ;-)
Tieto dve čísla sú neporovnateľné.

**Comment by 61Stan** [comment]
Porovnávam (u mňa na localhost):
Tabuľka č. 26. Informácie k časti G písm. c) a d) prílohy č.3 o záväzkoch s Účtovná závierka Úč POD v.2014, pričom nesedí riadok 122 (závierka) s Krátkodobé záväzky spolu a riadok 102 (závierka) s Dlhodobé záväzky spolu.
Tabuľka č. 35. Informácie k časti H písm. a) prílohy č.3 o tržbách s Účtovná závierka Úč POD v.2014 (výkaz ziskov a strát), pričom nesedí súčet riadov 03, 04 a 05 s "Spolu" v tabuľke č. 35.

**Comment by eurosecom** [comment]
V poznamkach POD je tabulka 26 napocitana zo saldokonta a obratovky, ucty su tam natvrdo podla poucenia, ktore nemozem najst lebo nebolo na githube, neda sa to ale generovat doporucujem upravit podla suvahy POD... okrem datumu splatnosti lebo ten je len v saldokonte

tabulka 35 su VYBRANE ucty trzieb za tovar, sluzby a vyrobky to je nieco ine ako cisty obrat bez zliav v r01 vo VZaS, podla mna neporovnatelne

**Comment by eurosecom** [comment]
K hodnotam napocitanym v Poznamkach POD mám každoročne veľa teórií o tom aká číslo má byť v niektorom riadku niektorej tabuľky a na jeden konkrátny riadok ich je vždy viac... myslím, že všetci užívatelia majú svoju pravdu a preto sme urobili poznámky upravovateľné - ak niekto nesúhlasí s napočítaným číslom môže si ho upraviť, na DU určite jeho prácu niekto ocení... V tomto zmysle sa snažím vybavovať reklamácie k hodnotám v tabuľkách poznámok...
