### ISSUE TITLE
Účto Predvolené texty - počet

### ISSUE THREAD

**Issue by 61Stan** [eurosecom/projekt1#78]
Dá sa v programe - užívateľsky - zvýšiť počet predvolených textov, ktoré sa zobrazia na výdavkom pokladničnom doklad - cez šedú ikonu? Aspoň na 20.

**Comment by eurosecom** [comment]
je to neobmedzene, skusal som 21, nie je problem ale...
po 20 polozke uz musi odskrolovat lebo na mojom displayi ta 21. polozka je uz pod spodnou hranou obrazovky
uzivatelovi sa moze zdat ze max 20
