### ISSUE TITLE
KVDPH zaokrúhlenie súčtového riadku

### ISSUE THREAD

**Issue by 61Stan** [eurosecom/projekt1#86]
V kontrolnom výkaze DPH v súčtovom riadku program nesprávne zaokrúhli hodnotu. Príklad v prílohe 
![kvdph_zle_zaokruhlenie](https://cloud.githubusercontent.com/assets/8523540/7745498/e888c582-ffab-11e4-9cd3-84f8b27cb7a2.png)

**Comment by eurosecom** [comment]
napíš doménu, firmu a obdobie aby som vedel odskúšať...

**Comment by 61Stan** [comment]
stavoimpexsro.sk
firma 130
4.mesiac
